vscode:
  extensions:
    - ms-python.python
    - ms-python.vscode-pylance
    - formulahendry.auto-close-tag
    - ms-toolsai.jupyter
    - batisteo.vscode-django
    - donjayamanne.githistory
    - esbenp.prettier-vscode
    - ecmel.vscode-html-css
