# Generated by Django 3.2 on 2022-08-11 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='user',
        ),
        migrations.AddField(
            model_name='userentry',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle', to='profiles.userprofile'),
        ),
    ]
