# Generated by Django 3.2 on 2022-08-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_has_sizes'),
        ('raffle', '0002_auto_20220811_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.collection'),
        ),
    ]
