# Generated by Django 3.2 on 2022-08-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
