# Generated by Django 3.2 on 2022-08-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220807_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
